"""
make_local_index.py -- a local contents page for the untracked deliverables.

The site is index.html and nothing else. The matched-pairs and charts pages are
working deliverables, not part of the site, so they are gitignored -- they are
fully regenerated by build_all.py from raw_data/ and scripts/, both of which are
tracked, so committing them would only be storing a derived copy that can go
stale against its own source.

That leaves them hard to find on disk. This writes deliverables.html at the repo
root: plain links to every generated page and data file, grouped by the task
that produced it, with the generating command next to each group so a missing
file tells you what to run rather than just 404ing.

deliverables.html is itself gitignored -- it points almost entirely at ignored
files, so tracking it would put a broken link table in the repo for anyone who
has not run the build.

Output: deliverables.html  (repo root, untracked)
"""

import os
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# (heading, command that produces the group, [(path, label), ...])
GROUPS = [
    ("The site", "python3 scripts/make_benchmark_doc.py", "tracked", [
        ("index.html", "The Benchmark Line — the front page"),
        ("output/benchmark_view.html", "same page, artifact form (no document skeleton)"),
        ("output/benchmark_data.json", "the payload embedded in both"),
    ]),
    ("Task 2 — master table", "python3 scripts/build_master_table.py [--window fy]",
     "tracked", [
        ("output/master_table.xlsx", "Apr–Sep 2020–2025 · 120 rows · Master table + Sources tabs"),
        ("output/master_table.csv", "same, CSV"),
        ("output/master_table.json", "same, JSON"),
        ("output/master_table_fy.xlsx", "fiscal year 2020–2024 · 98 rows"),
        ("output/master_table_fy.csv", "same, CSV"),
        ("output/master_table_fy.json", "same, JSON"),
        ("output/sources.csv", "source tab: exact CIHI/StatCan tables and download dates"),
        ("output/sources_fy.csv", "same, fiscal-year filters"),
    ]),
    ("Task 3 — matched pairs", "python3 scripts/matched_pairs.py [--tag _fy]",
     "untracked", [
        ("output/matched_pairs.html", "Matched Pairs Register — all 18 Apr–Sep pair-years"),
        ("output/matched_pairs_fy.html", "Same Volume, Different Waits — the 6 fiscal-year pairs"),
        ("output/matched_pairs.xlsx", "4 tabs: the rule, surviving pairs, summary, six-year detail"),
        ("output/matched_pairs_fy.xlsx", "same, fiscal year"),
        ("output/matched_pairs.csv", "surviving pair-years, Apr–Sep"),
        ("output/matched_pairs_fy.csv", "surviving pair-years, fiscal year"),
        ("output/pair_year_detail.csv", "all six years per surviving pair, with survives_rule flag"),
        ("output/pair_year_detail_fy.csv", "same, fiscal year"),
    ]),
    ("Task 4 — charts", "python3 scripts/make_charts.py", "untracked", [
        ("output/charts.html", "The Ninetieth Percentile — headline, trend, per-pair charts"),
        ("output/charts_data.json", "its payload"),
    ]),
    ("Task 1 &amp; 5 — written", "—", "tracked", [
        ("docs/TASK1_window_and_provenance.md", "reporting window and provenance findings"),
        ("docs/TASK5_limitations.md", "limitations page"),
        ("README.md", "repo guide"),
    ]),
]


def main():
    rows = []
    missing = 0
    for title, cmd, tracked, items in GROUPS:
        cells = []
        for rel, label in items:
            exists = os.path.exists(os.path.join(ROOT, rel))
            if not exists:
                missing += 1
            state = "" if exists else ' <span class="gone">not built</span>'
            link = (f'<a href="{rel}">{rel}</a>' if exists
                    else f'<span class="dead">{rel}</span>')
            cells.append(f"<li>{link}{state}<span class=\"lab\">{label}</span></li>")
        badge = ("tracked in git" if tracked == "tracked"
                 else "gitignored — rebuild with the command above")
        rows.append(
            f'<section><div class="h"><h2>{title}</h2>'
            f'<span class="badge {tracked}">{badge}</span></div>'
            f'<code class="cmd">{cmd}</code><ul>{"".join(cells)}</ul></section>'
        )

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Deliverables — local index</title>
<style>
:root{{color-scheme:light dark;--bg:#f4f4f1;--card:#fcfcfb;--ink:#0b0b0b;
  --ink2:#52514e;--mut:#898781;--rule:rgba(11,11,11,.12);--acc:#2a78d6;--gone:#d03b3b}}
@media(prefers-color-scheme:dark){{:root{{--bg:#0d0d0d;--card:#1a1a19;--ink:#fff;
  --ink2:#c3c2b7;--mut:#898781;--rule:rgba(255,255,255,.14);--acc:#3987e5;--gone:#e66767}}}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);
  font:15px/1.6 "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif}}
.wrap{{max-width:860px;margin:0 auto;padding:44px 22px 70px}}
h1{{font-size:30px;letter-spacing:-.02em;margin:0 0 6px}}
.sub{{color:var(--ink2);margin:0 0 28px;max-width:62ch}}
section{{background:var(--card);border:1px solid var(--rule);padding:16px 18px;margin-bottom:14px}}
.h{{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap;margin-bottom:8px}}
h2{{font-size:17px;margin:0}}
.badge{{margin-left:auto;font:10px/1 ui-monospace,Menlo,monospace;letter-spacing:.07em;
  text-transform:uppercase;color:var(--mut);border:1px solid var(--rule);padding:4px 7px}}
.badge.tracked{{color:var(--acc);border-color:var(--acc)}}
code{{font:12px ui-monospace,Menlo,monospace;color:var(--ink2)}}
code.cmd{{display:block;font-size:11.5px;line-height:1.5;color:var(--mut);
  padding:7px 9px;background:var(--bg);border:1px solid var(--rule);margin-bottom:10px;
  overflow-x:auto}}
ul{{list-style:none;margin:0;padding:0}}
li{{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap;padding:5px 0;
  border-bottom:1px solid var(--rule)}}
li:last-child{{border-bottom:none}}
a{{color:var(--acc);font:12.5px ui-monospace,Menlo,monospace;text-decoration:none}}
a:hover{{text-decoration:underline}}
a:focus-visible{{outline:2px solid var(--acc);outline-offset:2px}}
.dead{{font:12.5px ui-monospace,Menlo,monospace;color:var(--mut);text-decoration:line-through}}
.gone{{font:10px ui-monospace,Menlo,monospace;color:var(--gone);text-transform:uppercase;
  letter-spacing:.06em}}
.lab{{color:var(--ink2);font-size:13px;margin-left:auto;text-align:right;flex:1 1 210px}}
footer{{margin-top:26px;color:var(--mut);font-size:12.5px}}
</style></head><body><div class="wrap">
<h1>Deliverables</h1>
<p class="sub">Local contents page for this working tree. Only the site and the master
tables are tracked in git; the matched-pairs and charts pages are gitignored and
regenerate from <code>raw_data/</code> plus <code>scripts/</code>. This file is
generated and untracked too.</p>
{''.join(rows)}
<footer>Generated {date.today().isoformat()} by <code>scripts/make_local_index.py</code>.
Rebuild everything with <code>python3 scripts/build_all.py</code>.
{'' if not missing else f'<br><strong>{missing} file(s) not built yet</strong> — run the build.'}
</footer></div></body></html>
"""
    path = os.path.join(ROOT, "deliverables.html")
    with open(path, "w") as fh:
        fh.write(html)
    print(f"local index -> {path}")
    print(f"  {sum(len(g[3]) for g in GROUPS)} entries, {missing} not yet built")


if __name__ == "__main__":
    main()
